version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
    ports:
      - "${DB_SERVER_PORT}:${DB_SERVER_PORT}"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  app-network:
